PRECOMPILATION_GUIDE.md, mix.exs
This guide helps understanding the steps to get precompiled NIFs working
for package maintainers.
=> Add a precompilation guide

PRECOMPILATION_GUIDE.md, lib/rustler_precompiled.ex, mix.exs
Users only need Rustler when forcing the build.
Closes https://github.com/philss/rustler_precompiled/issues/11
=> Make Rustler an optional dependency

lib/rustler_precompiled.ex
This fix makes possible to compile the module without Rustler available.
The problem before this was because the macro was expanding the "use".
=> Fix usage of Rustler inside __using__ macro

PRECOMPILATION_GUIDE.md
The GH Action matrix in the precompilation guide can be tweaked a bit by using [a multi-dimension matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-a-multi-dimension-matrix) with another `nif` variable.
This can be seen in action [here](https://github.com/kloeckner-i/mail_parser/blob/main/.github/workflows/release.yml), for example.
=> Precompilation Guide: Use multi-dimension matrix 

lib/rustler_precompiled.ex
I made a mistake in #17 and removed `available_targets/0`:
https://github.com/philss/rustler_precompiled/blob/bb146da433b05d7192db732a0c9b10dc6d634074/lib/rustler_precompiled.ex#L156-L163
This causes `mix rustler_precompiled.download YourRustlerModule --all --print` to fail as it tries to download e.g. `libyour_rust_module_nif-v0.1.0-x86_64-unknown-linux-musl.so.tar.gz` without the NIF version.
Ideally we'd also have a test for it. I'll look into it but the cached metadata file makes it a bit tricky.
=> Fix `mix rustler_precompiled.download`

PRECOMPILATION_GUIDE.md
As per https://github.com/philss/rustler_precompiled/issues/21.
=> Mention latest cross in the precompilation guide

PRECOMPILATION_GUIDE.md
The precompilation guide gives an example about paths to include in the `mix.exs` package section prior publishing on hex.pm.
However, the `native` path could contain directories such as `target` which are not needed in the hex.pm package.
This PR makes the example more specific by only adding `.cargo`, `src` and `Cargo.*` paths.
=> Be more specific about which paths to add from the native folder in the precompilation guide

lib/rustler_precompiled.ex, test/rustler_precompiled_test.exs
This commit adds support for the `redhat` Linux variant. This means targets such as:
- x86_64-redhat-linux-gnu
- amd64-redhat-linux-gnu
will be treated as `x86_64-unknown-linux-gnu`.
Closes #30.
=> Support the `redhat` Linux variant

lib/rustler_precompiled.ex, test/rustler_precompiled_test.exs
This is a fix for the examples in the `target/0` function.
Closes https://github.com/philss/rustler_precompiled/issues/31
=> Using default targets for `target/0`

lib/rustler_precompiled.ex, test/rustler_precompiled_test.exs
This makes the metadata file available for mix tasks, making the process of releasing a new version easier.
So even if "force compilation" is used, we always have the metadata file available.
Closes https://github.com/philss/rustler_precompiled/issues/27
=> Always write the metadata file in compilation

lib/rustler_precompiled.ex, test/rustler_precompiled_test.exs
This is going to enable the process of building the metadata even if the current target is not available, but "force_build" is true.
Closes https://github.com/philss/rustler_precompiled/issues/38
=> Fix "force build" with unavailable target

lib/rustler_precompiled.ex, test/rustler_precompiled_test.exs
Add support for SUSE linux target:
`x86_64-suse-linux-gnu`, which will be aliased to `x86_64-unknown-linux-gnu`.
See #32  and #30
=> Add support for suse linux target

lib/rustler_precompiled.ex, test/rustler_precompiled_test.exs
For 64-bit RISC-V platforms, Nerves passes `riscv64` for the
architecture since that matched the tools (gcc and zig) used when Nerves
was ported to RISC-V. Rust uses `riscv64gc`. The `g` and `c` refer to
instruction sets available on the RISC-V processor, so this is a more
specific name. The `g` says that the processor supports atomics, integer
and floating point math. The `c` shows support for compressed
instructions. To my knowledge, all available 64-bit RISC-V processors
support `gc`, so this is a safe mapping.
=> Map riscv64 to riscv64gc to match Rust naming

lib/rustler_precompiled.ex, lib/rustler_precompiled/config.ex, test/rustler_precompiled/config_test.exs, test/rustler_precompiled_test.exs
Similar to how we have the option "targets" that can configure the supported targets, this commit adds a "nif_versions" option.
Fixes #41
=> Add option to configure NIF versions

lib/rustler_precompiled/config.ex, test/rustler_precompiled/config_test.exs, test/rustler_precompiled_test.exs
People using Alpine Linux containers on Apple machines with M1/M2 processors should benefit from this.
Closes #35
=> Add `aarch64-unknown-linux-musl` as a default target

lib/rustler_precompiled/config.ex, test/rustler_precompiled/config_test.exs, test/rustler_precompiled_test.exs
This is because more machines with RISC-V CPUs are arriving, and they are good for Nerves projects, since they are cheaper then Raspberry Pis.
In this commit there is also a change to prevent duplicated values, since people may already added some of the targets that are in the list of defaults.
Closes https://github.com/philss/rustler_precompiled/issues/44
=> Add `riscv64gc-unknown-linux-gnu` as default target

PRECOMPILATION_GUIDE.md, lib/rustler_precompiled.ex, lib/rustler_precompiled/config.ex, test/rustler_precompiled/config_test.exs
That version is targeting OTP 21, which is fairly old. We can speed up the release time of libs without this version.
=> Remove version "2.14" from the default NIF versions

lib/rustler_precompiled.ex, lib/rustler_precompiled/config.ex, test/rustler_precompiled/config_test.exs, test/rustler_precompiled_test.exs
As discussed in https://github.com/elixir-nx/explorer/pull/618, this adds support for freebsd.
`amd64-portbld-freebsd13.1` will be normalized to `x86_64-unknown-freebsd`.
Let me know what you think.
=> Add support for freebsd

lib/rustler_precompiled.ex, lib/rustler_precompiled/config.ex, test/rustler_precompiled/config_test.exs, test/rustler_precompiled_test.exs
Normally users need to build only for the lowest NIF version, unless they need specific features from newer versions.
=> Change defaults for upcoming v0.7

lib/rustler_precompiled.ex
This is a feature that can help people with internet access restrictions or writing permission limitations.
It may help people that need to support systems running on NixOS or a Nix environment.
In a nutshell, first download the desired ".tar.gz" artifact for a given package, set the `RUSTLER_PRECOMPILED_GLOBAL_CACHE_PATH` to the directory that the package was downloaded, and then build your project normally.
=> Add support for setting a global cache path using an env var

lib/mix/tasks/rustler_precompiled.download.ex
Also ensure the module is compiled ~~or the beam file for it exists~~.
This may close https://github.com/philss/rustler_precompiled/issues/69
=> Configure and compile the app in the mix task "rustler_precompiled.download"

lib/rustler_precompiled.ex, lib/rustler_precompiled/config.ex, test/rustler_precompiled_test.exs
The :base_url attribute now accepts static headers or a custom function that returns a URL and headers. This allows us to fetch NIFs from more complicated sources, rather than just public GitHub releases.
#65
=> Add support for headers and dynamic base URL (#65)

CHANGELOG.md, lib/mix/tasks/rustler_precompiled.download.ex, lib/rustler_precompiled.ex, test/rustler_precompiled_test.exs
There was a missing piece in the refactor to add support for headers in v0.8.
This is a fix for https://github.com/philss/rustler_precompiled/issues/82
=> Fix rustler_precompiled.download mix task - use correct function

lib/rustler_precompiled.ex
Super simple change to override the `:castore` use with the Hex ca store env var when set by a user. Needed by those behind corporate firewalls who typically have to set their own CA certs
=> added ca cert override via env var

lib/rustler_precompiled.ex
This is a minor change which makes working with Nix a little bit easier.
`write_metadata/2` passes a failed file write to its caller, `__using__/2`, which logs it as a warning. This is great, but on Nix the `File.mkdir_p/1` fails before we get there, and currently this causes the whole process to abort.
This PR just forwards any error from `File.mkdir_p/1` to the caller instead of raising a `MatchError`.
=> don't assume File.mkdir_p succeeds when writing metadata.

lib/rustler_precompiled/config/available_targets.ex
Hey :)
I needed a couple of new apple targets (specifically `["aarch64-apple-tvos-sim", "aarch64-apple-visionos",
"aarch64-apple-visionos-sim"]`) but since the module docs told me to re-run `rustc --print target-list` and I'm a good boy, this PR has a lot more changed targets :)
I was running this on `rustc 1.88.0 (6b00bc388 2025-06-23)`- I'm happy to re-run on any other rust version and/or cheery-pick only the targets I specifically need if that makes your life easier 💚
=> update targets list
